USE MASTER
GO 
CREATE DATABASE Users
GO 
USE Users
GO
CREATE TABLE User_Table(
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Username NVARCHAR(20) NOT NULL,
[Password] NVARCHAR(20) NOT NULL,
[Firstname] NVARCHAR(20) NOT NULL,
[Lastname] NVARCHAR(20) NOT NULL,
Age INT NOT NULL,
)